### ISSUE TITLE
When creating a new metering point, it also triggers the creation of a new grid 

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#126]
### Current Behavior

When creating a metering point it triggers the class "GridAreaId", which creates a new grid area using a GUID. Creating a new MP should not trigger the creation of a new grid area, but indicate in the DB which grid area the MP is created in. The format of a grid area is also always precisely 3 digits, and not a GUID. 

If the grid area indicated is valid and exists is performed in the create MP Validation rules. 

Actually creating and storing an overview of grid areas is currently out of scope.

### Expected behavior

We need to indicate the grid area as received in the input XML messages in both our MeteringPoints DB and in our integration event. We need to not create a new grid area at this time. The creation of a grid area will never be tied to the creation of a MP.

### How to reproduce

Trigger creation of new MP with valid data (including 3 digit grid area)
See that a new grid area using GUID format is created and stored in both DB and Integration event

### Environment

All

### Possible Solution

Have list of grids provided by mighty ducks in seperate table. Implement relevant validations checking if incoming request is for a existing grid.

**Comment by Christian-Meyer** [comment]
Talk to business about GRID areas and how to handle it.

**Comment by erduna** [comment]
Being fixed as part of grid areas in PI6.
