### ISSUE TITLE
Creation of CIM messages for accept and reject

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#153]
`RequestMoveInResultHandler` must be updated to generate Accept/Rejcet messages in CIM XML format, and place them in Outbox.

**Comment by Christian-Meyer** [comment]
@cmgrd  @kft  Please update with tasks :)

**Comment by erduna** [comment]
Do the cim messages need to go in the outbox? Shouldn't we just generate the xml and in the outbox point to the location?
