### ISSUE TITLE
We must be able to send information to the balance supplier when a consumption metering point has been connected

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#173]
As a balance supplier
We want to be able to receive information when a metering point has been connected
So that we know the metering point has been connected and can start delivering power to the metering point

**Description**

After the approval of a request for change metering point status from newly created to connected, the balance supplier must receive information about the metering point being connected. The action takes place after the metering point has been connected. We send an RSM-022 to the balance supplier.

**Acceptance criteria**

When a consumption metering point is connected
- [ ]  we can generate a message to the balance supplier with information about the connection status

**Comment by Christian-Meyer** [comment]
Hey Team. @kft @Korgath @cmgrd @thbaan @erduna 

As talked about the other day, we also need to complete this story.

I have created it is a story, if you could break it down into tasks I would be happy :)

**Comment by erduna** [comment]
We miss a recipient and the occurrence date. 

We need to set the GLN number of the supplier when listening to the supplier changed event from market roles before we can set a recipient. Probably also a read model. 

Other than that the message is generated.
