### ISSUE TITLE
To and From grid not set in integration event when creating an exchange MP

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#228]
### Current Behavior

When creating an E20 (Exchange) MP, the to and from grid in the integration event is left empty. 

They are registered in the DB correctly.

### Expected behavior

To and From grid needs to be included in integration event, and not empty.

### How to reproduce

Create an exchange MP. 

### Logs

The integration event sent out:
{"Gsrn":"571313180400021143","MeteringPointType":"Exchange","GridAreaId":"6c9227d4-acb1-4fda-87fd-e5f6db9670a6","SettlementMethod":"","MeteringMethod":"Physical","ConnectionState":"New","MeterReadingPeriodicity":"Hourly","NetSettlementGroup":"","ToGrid":"","FromGrid":"","Product":"Tariff","QuantityUnit":"KWh","ParentGsrn":"","EffectiveDate":"2021-08-13T09:59:03Z"}

### Environment

Dev

**Comment by thbaan** [comment]
We need to discuss the solution for this bug. Right now we publish a domain event in MeteringPoint base class. We need to publish this event in the concrete implementations of MeteringPoint (e.g. ExchangeMeteringPoint), but most fields on base are private.
