### ISSUE TITLE
Using connect MP process with disconnect code (E23) still results in a connected metering point

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#257]
### Current Behavior

Sending in a request to connect an MP (Process type D15), but using the disconnection code (E23) still results in the metering point being connected, and a Metering point connected integration event to be sent out.

### Expected behavior

Any other code than "Connect" (E22) using the process type D15 (connect metering point) should be rejected.

### How to reproduce

Send in a request to connect a metering point in state "New", but use the disconnect code instead (E23)

### Environment

U

**Comment by Christian-Meyer** [comment]
Look into if we will provide this service for market.

**Comment by Christian-Meyer** [comment]
We do not need to perform checks that are not part of the process. Talk to CCO

**Comment by Christian-Meyer** [comment]
Has been fixed
