### ISSUE TITLE
Missing input validation 🤔

### ISSUE THREAD

**Issue by Sondergaard** [Energinet-DataHub/geh-metering-point#290]
It's not clear to me if the input is validated before reaching this point:
https://github.com/Energinet-DataHub/geh-metering-point/blob/0257beb62c65214457c1e54dd8d2aa801d836fda/source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs#L199

If not there are multiple reasons why this code might fail. The supplied value is `null`, empty string, only spaces or any other character that the `int.Parse` method is not able to handle. Any way, it will yield an exception.

**Comment by Christian-Meyer** [comment]
@kft Can you take a look at this?
