### ISSUE TITLE
Message Queue Handling

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#32]
### Is your feature request related to a problem? Please describe.
This is related to create metering point. 
Related to ingestion part. 
Talk to @Korgath 

### Describe the solution you'd like.
- [x] Add Message Queue Envelope (MessageQueueItem), that contains:
     - [x] UserIdentity (add via context)
     - [x] CreateMeteringPointCommand
     - [ ] _CommandType_ (won't implement directly, using protobuf contract instead)
- [ ] Add interface: _IMessageQueueService_ (won't implement directly, using messaging transport "framework")
- [x] Create concrete implementation with ServiceBus: MessageQueueService
- [x] Add to DI
- [x] Retry handling - Polly

### Definition of done
- [x] Demonstrate that item can be added to underlying queue (ServiceBus)
- [ ] Demonstrate that retry handling works
- [x] Manual test

**Comment by Christian-Meyer** [comment]
@erduna Does this issue need more testing?

**Comment by erduna** [comment]
Haven't explicitly demonstrated retry handling, but I think we can close this anyways :)
