### ISSUE TITLE
BusinessProcessResult

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#33]
### Is your feature request related to a problem? Please describe.
This is part of create metering point

### Describe the solution you'd like.
- [x] Generel object that is returned after completion of validations
     Contains
   - [x] List of validations errors (Not EDI Codes - must be descriptive)
   - [x] Look into ID's and agree on terms.  (setup meeting with business)
   - [x] Suceeded
   - [x] TransactionID 
   - [ ] Process ID

			

### Definition of done
- [x] Demonstrate that Succeeded = true if there is not any errors and false if there are errors

**Comment by Renetnielsen** [comment]
No hablo Danés

**Comment by Renetnielsen** [comment]
![image](https://user-images.githubusercontent.com/3541298/116365104-37d5e680-a805-11eb-8012-793992a4fc7f.png)

**Comment by Christian-Meyer** [comment]
Lo siento. Está traducido al inglés.
