### ISSUE TITLE
Authorization validation

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#36]
### Describe the solution you'd like.
- [x] Start by getting an overview of validation rules (see comments)
- [ ] Implement authorization validations rules from comments

### Describe alternatives you've considered.
- [ ] Unit tests for the different validations rules

**Comment by erduna** [comment]
I believe this is the only rule that might qualify under the term authorization:

- The metering grid area of a metering point must belong to the correct grid operator
