### ISSUE TITLE
CreateNewMeteringPointConfirmation and CreateNewMeteringPointReject contains wrong data

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#418]
### Current Behavior

Processtype is currently hardcoded to be "E65". The actual process of creating a new metering point is "E02". The Process type should not be hardcoded, as the same document will be used for many processes.

The role of the recipient is hardcoded to be DDQ. It can never be DDQ. Instead we should use the role indicated in the incoming request. Follwing field in XML is used to indicate actor role:

<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>

### Expected behavior

* The actual process of creating a new metering point is "E02". This information should not be hardcoded.
* Actual role of actor sending in the create metering point request should be used.

### How to reproduce

Send in a succesful and a non-succesful create metering point request to view generated messages.

### Environment

U

### Additional context/screenshots

![image](https://user-images.githubusercontent.com/25637982/138830483-697a93ba-3799-4809-b992-82264fc1a943.png)

**Comment by cmgrd** [comment]
Process type fixed with #541. Roles will be fixed with the actor registry.
