### ISSUE TITLE
Missing disconnection type results in 500 internal server error instead of actual validation error

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#422]
### Current Behavior

Not including disconnection type results in 500 internal server error.

### Expected behavior

It should result in an actual validation error and a resulting rejection document.

### How to reproduce

Send in a request without disconnection type

### Environment

U

### Possible Solution

The rule is implemented, we just never use it. Just needs to be registered on market document level.

**Comment by erduna** [comment]
Missing to make nullable in MasterDataDocument.cs

**Comment by Korgath** [comment]
Used in Ruleset for Create metering point
![image.png](https://images.zenhubusercontent.com/60ae3dc186f9224f4cc8b7d8/31c07747-3925-4e94-86e1-5deac203f4ec)
