### ISSUE TITLE
Exchange metering point does not handle geo info reference or actual address indicator

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#423]
### Current Behavior

Currently geo info reference (DAR reference) for exchange metering points is unhandled. It's always left as null even when a value is sent, and the actual address indicator defaults to false.

### Expected behavior

Geo info reference is mandatory and needs to be handled for exchange metering points. When a reference is included it should not be saved as null.

### How to reproduce

Send in a exchange MP request with valid geoinforeference and actual address indicator set to true.

### Environment

U

**Comment by erduna** [comment]
When geo info reference is present it rejects with the following error:

"Geo info reference is required for this type of metering point"

**Comment by Christian-Meyer** [comment]
Solved
