### ISSUE TITLE
Rejection message has wrong reason code format in header

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#424]
### Current Behavior

Reson code in header has following format currently:
![image](https://user-images.githubusercontent.com/25637982/139055768-e626c0ec-9490-4c10-9753-87819fa60183.png)

### Expected behavior

Expected format:
![image](https://user-images.githubusercontent.com/25637982/139055898-d5aed66c-2ee0-4df4-8b76-91d42fb61066.png)

**Comment by cmgrd** [comment]
Fixed with #541
