### ISSUE TITLE
Sending in anything but an int for townDetails>code throws an exception in processing

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#430]
### Current Behavior

![image](https://user-images.githubusercontent.com/25637982/139077699-9a0d92d4-75e5-4b3b-8d55-f6493523fc3b.png)
Sending in a string (or other non int format) in the code field results in an exception being thrown in processing regarding wrong input format:
![image](https://user-images.githubusercontent.com/25637982/139077854-8e807dc1-f0c4-4df3-b2da-3366d1b6d6b8.png)

No actor messages are generated.

### Expected behavior

Wrong input format should result in a actor rejection message.

### How to reproduce

Send in any create MP request with any type other than int in the townDetails>code field.

### Environment

U

**Comment by Korgath** [comment]
Doesn't behave as desribed any more
