### ISSUE TITLE
Sending in anything but an int for contractedConnectionCapacity or ratedCurrent results in a 400 Bad Request

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#431]
### Current Behavior

Sending in anything but an int for contractedConnectionCapacity or ratedCurrent results in a 400 Bad Request

### Expected behavior

Any invalid input for a field should result in a rejection message to the requesting actor, and not a bad request.

### How to reproduce

Send in any create mp request with a non integer value in contractedConnectionCapacity

### Environment

U

**Comment by Korgath** [comment]
This will be fixed with the XML Schema validation
