### ISSUE TITLE
We are able to create special metering point types

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#437]
**Benefit hypothesis**

As a grid company
We want to be able to send in a request to create special metering point types, and get our message validated.
So that we can be informed if our request contains errors.

**Description**
We want to be able to receive a request from a grid company about the creation of special metering point types. The purpose of this story is to be able to validate the message and generate either an accept message if the request is approved or a reject message if the request contains errors.
Link to Master Data document
https://teams.microsoft.com/l/file/08E8D946-ED1D-472E-9341-C3AC1A519778?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&fileType=xlsx&objectUrl=https%3A%2F%2Fenerginet.sharepoint.com%2Fsites%2FDH3ART-team%2FDelte%20dokumenter%2FTeam%20Batman%2FKopi%20af%20~%2015_00718-192%20Stamdata%20engros%20plus_vers.%206%207978087_12_0.xlsx&baseUrl=https%3A%2F%2Fenerginet.sharepoint.com%2Fsites%2FDH3ART-team&serviceName=teams&threadId=19:3ed744011a2043498a1f219e19da45f4@thread.tacv2&groupId=e1b7877a-ee7d-4505-a4b2-4989abc2d22a

**Acceptance criteria**
- [x] We can receive a request for creation of the following MP types:
- [x] We are able to create "VE production" (D01)
- [x] We are able to create "Analysis" (D02)
- [x] We are able to create "Surplus production group 6" (D04)
- [x] We are able to create "Net production" (D05)
- [x] We are able to create "supply to grid" (D06)
- [x] We are able to create "Consumption from grid" (D07)
- [x] We are able to create "Whole sale services/information" (D08)
- [x] We are able to create "Own production" (D09)
- [x] We are able to create "Net from grid" (D10)
- [x] We are able to create "Net to grid" (D11)
- [x] We are able to create "total consumption" (D12)
- [x] We are able to create "Electrical heating" (Er sin egen user story, men den er med her, så I tænker den ind)
- [x] We are able to create "Net consumption" (D15)
- [x] We are able to create "Other consumption" (D17)
- [x] We are able to create "Other production" (D18)
- [x] We are able to create "Exchange reactive energy" (D20)
- [x] If the request fails one or more validation the request is rejected and a reject message adhering to relevant CIM format is created.
- [x] If the request passes validations an accept message adhering to relevant CIM format is generated and the exchange metering point is created

**Validations applicable for all special MP types**
- [ ] The power plant of a metering point is mandatory for D01 (Error code D57)
- [x] The power plant of a metering point is a valid GSRN/EAN18 code (checksum) that starts with digits ´57´ (Error code D02) (Error code D02)
- [x] The meter number of a metering point consists of maximal 15 characters (Error code E86)
- [x] The capacity of a metering point consists of maximal 8  characters. Only digits and an optional decimal point are allowed. (error code E86) (must be 9 characters)
- [x] The measure unit must be kWh if the master data does not apply to a metering point of type VE Production (D01), Analysis (D02), Other consumption (D17), Other production (D18), Exchange - Reactive energy (D20) or Internal use (D99) (error code E73)
- [ ] For an Own production (D09) child metering point for which the parent metering point is not in net settlement group 0 or 99 the sub type must be Virtual (D02) or Calculated (D03). (error code D37) _We can probably first implement it when we look at adding parent/child relation, but I have kept it here, so you are aware of the validation._
- [ ] Total consumption metering points (D12) must be Virtual (D02) or Calculated (D03). (error code D37)
- [ ] If type of metering point is Net consumption (D15) then meter reading occurrence must be Hourly (PT1H). (Error code D23)
- [ ] If type of metering point is Surplus production group 6 (D04) then meter reading occurrence must be Hourly (PT1H). (Error code D23)
- [ ] If type of metering point is Net consumption (D15) then sub type must be Calculated (D03). (error code D23) 
- [ ] The AssetType has domain values D01 – D20 or D99 (error code D59)
- [ ] The energy time series measure unit must be kWh or MWh if the master data applies to a metering point of type Other consumption (D17) or Other production (D18) (error code E73)
- [ ] If type of metering point is Other consumption (D17) or Other production (D18) then sub type must be Physical (D01) or Virtual (D02). (Error code D37)

**Comment by Christian-Meyer** [comment]
@Korgath I have removed validations that are implemented in other stories.

**Comment by Christian-Meyer** [comment]
Validations not implemented in this story have been moved to #486

**Comment by erduna** [comment]
See following bug:
https://github.com/Energinet-DataHub/geh-metering-point/issues/501
