### ISSUE TITLE
Differences in schemas across metering point types

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#45]
### Question
Ermin - How large are the differences on schemes (EDI) across metering point types - We need to look into this in order to decide if we can handle all metering point types in the same cmd object

**Comment by erduna** [comment]
This is all possibilities: 

![image](https://user-images.githubusercontent.com/25637982/116401947-1cca9d00-a82c-11eb-807c-97af7fe1eed9.png)

It makes sense to do it in the same cmd object, as I assume our flow is triggered based on MP type anyways. Note that the message initiating create metering point has BusinessReasonCode = E02.

**Comment by erduna** [comment]
Hope this is higher resolution:

![Billede1](https://user-images.githubusercontent.com/25637982/116402257-792dbc80-a82c-11eb-933a-29054e32eb16.jpg)

**Comment by erduna** [comment]
We have just confirmed that we will internally not be using ebix, but CIM XML. I have reached out for an example of RSM-021 in CIM XML.
