### ISSUE TITLE
Implement RequestFailure message to MessageHub if they make an erroneous request

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#456]
### Is your feature request related to a problem? Please describe.

If the message hub makes an erroneous peek request, we currently throw an exception and the messagehub request times out. We need to respond with a relevant error reason, so that the message hub can act accordingly, instead of repeating the same mistake over and over. 

Example:
If the messagehub request data with an Id we do not have available, following exception occurs in MP domain:
System.InvalidOperationException: Sequence contains no elements at System.Linq.ThrowHelper.ThrowNoElementsException() 

Run following query for full log:
union traces
| union exceptions
| where timestamp > ago(30d)
| where operation_Id == 'b1c2e9afcd967b4bb1658d04613e0e0e'
| where customDimensions['InvocationId'] == '0ae3d29f-4e10-49b8-aadc-50f5d24b55f5'
| order by timestamp asc
| project
    timestamp,
    message = iff(message != '', message, iff(innermostMessage != '', innermostMessage, customDimensions.['prop__{OriginalFormat}'])),
    logLevel = customDimensions.['LogLevel']

The request will timeout after 30 seconds, and messagehub will not know anything went wrong. Because of this they cannot cleanup any unavailable bundles, and any subsequent request will again request data which we do not have available.

### Describe the solution you'd like.

We need to implement the "RequestFailure" message as described here:
https://github.com/Energinet-DataHub/geh-post-office/blob/main/source/Energinet.DataHub.MessageHub.Model/source/Energinet.DataHub.MessageHub.Model/Protobuf/DataBundleResponseContract.proto

**Comment by Christian-Meyer** [comment]
@cmgrd Have we fixed this?

**Comment by Christian-Meyer** [comment]
@MrDach @Korgath Do you know if this is still an issue?

**Comment by Korgath** [comment]
@Christian-Meyer  Honestly, no idea what it even is x(
