### ISSUE TITLE
Schema validations in relation to EDI/Ebix

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#46]
### Question
Søren - Are we sure that schema validations in relation to EDI/Ebix ensures that deserializing goes well, So we can convert EDI to internal format in the incoming request (synchronous)

**Comment by Christian-Meyer** [comment]
I have assigned you to this question, Søren. You can reach out to Thomas and Kristian for elaboration.

**Comment by Sondergaard** [comment]
We need some clarifications about input and output data for the system. When this is settled we can start design the process for handling requests.

As of now, the schema validation for Ebix/RSM is only structure validation. This gives the developers a guarantee that Xml contains all the needed fields. but nothing about the content. As long as the conversion is about structure then it can be used. If you need to make assumptions about the content of a field, then it starts to get shaky.
