### ISSUE TITLE
The frontend must be able to receive data in CIM format

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#489]
**Description**
Currently the data received from metering point domain to frontend is internal representations of values.
The frontend must be able to receive data in CIM format so the data is readable for the end user.
We need to build it into the client so the translation happens when frontend request the data. 

**Acceptance criteria**
- [x] Be able to translate internal values to CIM values
- [x] Must be as classical enums

**Comment by LayZeeDK** [comment]
@thbaan @Christian-Meyer 
As an example, something like a `MeteringPointType` enum with the `Dxx` and `Exx` values declared as a return type in the Metering Point API client would be great.

A TypeScript frontend client is auto-generated based on the backend-for-frontend's OpenAPI specification so this would tremendously help us synchronize the contract between Metering Point domain, Backend-for-frontend, and Frontend.
