### ISSUE TITLE
Fix issues

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#497]
This task fixes some issues with validations and how they are treated.

Disconnection type gives 500 internal server error instead of validation error

Powerlimit is set as optional but must be mandatory

And ContractedConnectionCapacity or ratedCurrent results in 400 bad request.

See issues linked in dependency for descriptions.

**Comment by Korgath** [comment]
Removed #431 Sending in anything but an int for contractedConnectionCapacity or ratedCurrent results in a 400 bad request since it will be resolved with the implementation of schema validation
