### ISSUE TITLE
RSM-022 (AccountingPointCharacteristics) message has incorrect format for various types

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-metering-point#500]
### Current Behavior

The AccountingPointCharacteristics message currently does not reflect the differences between the MP types: 
![image](https://user-images.githubusercontent.com/25637982/143432195-a9db6d10-41c6-4aba-a7ce-5278480109df.png)

Red (illegal) fields are not allowed to be present in the message.

Yellow/purple (optional) fields have to be present in the message. If the data is null the fields still need to be included, but empty. 

A few of the yellow marked fields are only permitted as part of an answer to a data request (brs-005). See the attached excel sheet in tab "MP ud". They should be excluded when not as an answer to a request.

Finally, the "BalanceSupplerID" and "SupplyStart" fields are only allowed to be sent to the current energy supplier.

[Stamdata engros plus_vers. 6.XLSX](https://github.com/Energinet-DataHub/geh-metering-point/files/7602523/Stamdata.engros.plus_vers.6.XLSX)

**Comment by Christian-Meyer** [comment]
@cmgrd Do you know if RSM-022 needs to be updated according to above text? Is this still relevant or has it been fixed?
