### ISSUE TITLE
Child metering point

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/geh-metering-point#531]
### Synopsis: 

As a datahub user
I want view created child metering points
so that i can see related master data on that child metering point  

As a datahub user
I want view created child metering points
so that i can see related parent metering point

### Acceptance criteria:
- [x] Given a child metering point, when created in datahub, then a datahub user must be able to look it up in GUI and view related master data.
- [x] Given a child metering point is created, when coupled to a parent, Then the link to the parent metering point must be available on the page
- [x] Given a child metering point is created, when not coupled to a parent, then a link to a parent is not available on the page.
- [x] Given a child metering point is created, When that Metering point has chargelinks, then charge links are shown as a separate list on the page.  

Link to mock up:(https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=572%3A2014&viewport=241%2C48%2C2.95&scaling=contain&starting-point-node-id=572%3A2014&show-proto-sidebar=1)

- [x] Remove child specific route

**Use same route / page as metering point, with following modifications:**
- [x] Adjust breadcrumbs to align with prototype 
- [x] Remove "Har el leverandør" (primary master data)
- [x] Remove "Øvrige lokations detaljer" (secondary master data)
- [x] Re- move "child målepunkter" tab

### Links:

➡️ &nbsp;[Prototype](https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=562%3A2443&viewport=351%2C48%2C0.44&scaling=contain&starting-point-node-id=562%3A2396&show-proto-sidebar=1)

**Comment by MadsBloendAndersen** [comment]
@MadsBloendAndersen write synopsis
