### ISSUE TITLE
[Login] Authenticate user

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-metering-point#535]
Client ID: 88e5d356-0c71-49e9-b260-d0629f3c0445
Tenant ID: 240beb65-9291-4330-89a3-459d027df97c
Tenant domain name: dev002DataHubB2C.onmicrosoft.com

**Acceptance criteria:**
- [x] Local environment should run on HTTPS (SSL)
- [x] Catch login redirect from B2C, wildcard route
- [x] Redirect user to B2C, if not authenticated
- [x] Add logout button
- [x] Fix E2E tests
- [x] Fix unit / integration tests (Jest)

**Environments:**
u001 - https://jolly-sand-03f839703.azurestaticapps.net
u002 - https://ambitious-coast-027d0aa03.azurestaticapps.net

**Tech notes:**
Test user:
dikih65949@hagendes.com
Goga5727

[Create test users (B2C)](https://bit.ly/3t9S4l2)

~~**BLOCKED**: AADB2C90007: The application associated with client id '88e5d356-0c71-49e9-b260-d0629f3c0445' has no registered redirect URIs.~~

~~**BLOCKED**: We need a signIn userflow or custom policy to be able to continue** 
https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview
https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow~~

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten will refine this issue
