### ISSUE TITLE
[Login] Create login screen

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-metering-point#536]
**NB: Should be done by UI experts!**

Synopsis

As a meter data responsible 
I want to login to DataHub 
So that I can see created metering points
**Accept criteria:**
- [x] Custom layout page in B2C
- [x] Given a datahub user, When not logged in, Then you are redirected to Microsoft custom layout login page 
- [x] Given a datahub user, when you login and give correct login information, then you are redirected to search metering point screen. 
- [x] Given a new datahub user is created in B2C, when this user login and give correct login information, then you are redirected to the search metering point page.  

**Environments**
u001 - https://jolly-sand-03f839703.azurestaticapps.net
u002 - https://ambitious-coast-027d0aa03.azurestaticapps.net

**Tech note**: 
- [x] Route to login page
- [x] Joules developers has access to figma
- [x] This page is added as an asset in angular
- [x] [i18n](https://docs.microsoft.com/en-us/azure/active-directory-b2c/language-customization?pivots=b2c-user-flow)

https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-with-html?pivots=b2c-user-flow

https://thecodeblogger.com/2021/03/23/creating-custom-login-page-in-azure-ad-b2c/

New users can be created here: 
https://bit.ly/3t9S4l2

**Comment by MadsBloendAndersen** [comment]
@rasmusgothgen + @djorgensendk we need Daniel to configure custom layout for B2C (Login)
