### ISSUE TITLE
Metering point - formatting dates

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/geh-metering-point#543]
Acceptance criteria:

- [x] Create a shared pipe which formats our dates correctly in format dd-mm-YYYY (see comment from Mogens)
- [x] Use date-fns and date-fns-timezone if necessary (https://date-fns.org/v2.0.0-alpha.27/docs/Time-Zones) 
- [x] Use pipe in primary master data

Tech notes:
You can read more about pipes and how to create a custom pipe here: https://angular.io/guide/pipes

Mogens Juul Sass-Petersen:
> Jeg har spurgt DNI; MKB og JLI som også arbejder på Eloverblik GUI. De anvender vi 01-01-2022.
> Ligeledes skal alle datoer vises i armbåndsur tid. Så er der i systemet angivet 31-12-2021 23:00 skal det vises som 01-01-2022.

**Comment by ZavezX** [comment]
I talked to Christopher from Batman about this issue and we concluded that we can safely assume that all dates are in UTC format even though we don't get any information about it when receiving dates from Metering Point domain through API calls. 

The task changes its nature and we should handle the issue in BFF instead and format the date to have the format we want eg. `YYYY-mm-ddThh:mm:ssZ`
