### ISSUE TITLE
Language choice in the view metering point screen works opposite

### ISSUE THREAD

**Issue by khatozen** [Energinet-DataHub/geh-metering-point#586]
In the view metering point screen, when you chose the language “DA”, the text will be showed in English and vice versa:

![image.png](https://images.zenhubusercontent.com/6110f1589f04be24392a986f/680a0cf7-2a7a-4869-9f8b-34779d7ac3fb)

**Comment by MadsBloendAndersen** [comment]
@jonasdmoeller there you have it. :) Khatozen had the same thoughts as you.
