### ISSUE TITLE
Better overview/search for metering points

### ISSUE THREAD

**Issue by ZavezX** [Energinet-DataHub/geh-metering-point#607]
### Synopsis

As a datahub user
it is very unintuitive that I need to know an exact metering point gsrn number 
in order to use the UI

### Description

We can achieve a better user experience by doing one or more of the following things:
1. We could expand the search functionality to be able to search for multiple things and get a list of search results limited to the metering points for the logged in user (actor).
2. We could add a metering point list view with all the metering points for a given logged in user (actor), that the user can sort and select one from to view metering point details.

**Comment by ZavezX** [comment]
@MadsBloendAndersen I have a suggestion here to improve the user experience in the UI so it gets easier to use it and navigate through metering points. Would you take a look at it when you have the time and then we can discuss it next week? 

This is merely an improvement suggestion and it would be great if we could find the time to immplement some of it.

**Comment by MadsBloendAndersen** [comment]
@ZavezX You have a valid point. But I believe that i has been an active choice, to make the search possibilities so limited at the moment. But it will later be expanded to search for other things than metering point ID, such as , address, MP type, settlement method, grid area, parts of a MP id etc. 

But for now, we are only building the the absolute minimum to get by.

**Comment by MadsBloendAndersen** [comment]
@frontend-specialisten @dzhavat isn't that right?

**Comment by frontend-specialisten** [comment]
Yea that's right @MadsBloendAndersen
