### ISSUE TITLE
As a grid company we want to limit other grid companies, viewing our metering points in GUI

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-metering-point#634]
## Description
Grid companies can only find metering points they are responsible for in GUI.

For example: 

Grid company A are responsible for  grid area X, Y & Z.

Then grid company A is only allowed to see metering points created in grid areas X, Y & Z 

New users must be linked to a grid company organisation before they can find any metering points. 

One user can belong to multiple organisations. 

## Acceptance criteria
- [ ] Given grid company A creates MP1, When grid company B looks up MP 1 in GUI, Then grid company other than A, cannot find MP 1.
- [ ] Given Grid company A creates MP1, When creating a new user and connecting this user to grid company A's organisation, Then the new user is able to search and find MP 1
- [ ] Given Grid company A creates MP1, When creating a new user and the new user is not connected to Grid company A's organisation, Then the new user is not able to search and find MP 1.

**Comment by MrDach** [comment]
Talked with Martin, Mogens and Morten about how the setup for tieing users and actors together should look like.
Martins conclusion was that Metering Point should hold that data for now as part of the temporary test setup.
This will require a couple of new tables containing users and the relations and perhaps some hacky way to create these.
