### ISSUE TITLE
User test in meteringpointClient in BFF

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#697]
- [ ] Allow to programmatically "logging in" as a user in b2c (help wanted).
- [ ] Add helper class to generate token to be used in integration tests for frontend users
- [ ] Extend our "security tests" for the metering point client.

Was originally part of https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/150

**Comment by Christian-Meyer** [comment]
Hey @mknic would it be possible for us to get Daniels assistance on this story?

**Comment by mknic** [comment]
@Christian-Meyer sure. Would it be in the iteration starting February 21? 
@frontend-specialisten this might tap into the issue you've solved by having a test user as we discussed on planning?

**Comment by Christian-Meyer** [comment]
@mknic Yes, next iteration starting feb. 21

**Comment by Christian-Meyer** [comment]
@mknic Tasks have been updated. It is the first step we need help with. (He needs to do it) Currently we cannot login as users without a UI.

**Comment by mknic** [comment]
@djorgensendk please have a look at bullet one in the description. Would you mind creating an issue on our board if you know what it's all about?

**Comment by Christian-Meyer** [comment]
Look at issue linked by Dan, and check if this solves this issue.
