### ISSUE TITLE
Validation rules for create metering points

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-metering-point#71]
**Input Rules that are ready to be implemented**
- [x]   The identification of a metering point is mandatory
- [x]  - **The identification of a metering point is a valid GSRN/EAN18 code (checksum) that starts with digits '57'**
- [x]  - The identification of a metering point (GSRN) is unique within GEH (also historically) 
- [x]  - The metering grid area of a metering point is mandatory
- [x]  - The occurrence of a metering point is mandatory
- [x]  - The occurrence of a metering point has format YYYY-MM-DD HH:MI:SS (UTC+0)
- [x]  - **The metering grid area of a metering point consists of exactly 3 digits**
- [x]  - The type of a metering point is mandatory
- [x]  - The type of a metering point has domain values E17 (Consumption), E18 (Production), E20 (Exchange), D01 (VE production), D04 (Surplus production group 6), D05 (Net production), D06 (Supply to grid), D07 (Consumption from grid), D08 (Wholesale services / information), D09 (Own production), D10 (Net from grid), D11 (Net to grid), D12 (Total consumption), D13 (Grid loss correction), D15 (Net consumption), D17 (Other consumption), D18 (Other production), D20 (Exchange - Reactive energy), D02 (Analysis), D99 (Internal use)
- [x]  - The street code of a metering point consists of exactly 4 digits in the range 0001 to 9999
- [x]  - The street name of a metering point consists of maximal 40 characters
- [x]  - If country code is DK then the building number of a metering point consists of maximal 4 characters (range 1-999, A-Z, Æ, Ø, Å capitals only and no spaces), otherwise the building number consists of maximal 6 characters. (Refrase) 
- [x]  - The floor identification of a metering point consists of maximal 4 characters
- [x]  - The room identification of a metering point consists of maximal 4 characters
- [x]  - The city name of a Consumption and Production metering point is mandatory. It is optional for all other MP Types
- [x]  - The city name of a metering point consists of maximal 25 characters
- [x]  - The post code of a Consumption or Production metering point is mandatory, it is optional for all other MP Types
- [x]  - If country code is DK then the post code of a metering point consists of exactly 4 digits in the range 0000 to 9999 otherwise the post code consists of maximal 10 characters.
- [x]  - The city sub division name of a metering point consists of maximal 34 characters
- [x]  - The municipality code of a metering point consists of exactly 3 digits in the range 100 to 999
- [x]  - The country name of a metering point has domain values DK or empty (Denmark)
- [x]  - The settlement method of a metering point is mandatory if the MP is E17 (consumption) or D13, otherwise it is not allowed (we need to remove the part about D13 in the implemented rule, it is not applicable anymore)  Is already implemented 
- [x]  - The settlement method of a metering point has domain values E02 (Non profiled), D01 (Flex)
- [x]  - The meter reading occurrence of a metering point is mandatory (Types are defines in other validation rules)
- [x]  - The net settlement group of a metering point is mandatory for Consumption and Production MPs, otherwise not allowed
- [x]  - The net settlement group of a metering point has domain values 0, 1, 2, 3, 6,  and 99
- [x]  - The power plant of a metering point is mandatory for Production MP's
- [x]     The power plant of a metering point is mandatory for consumption if their net settlement group is not 0
- [x]  - The power plant field is mandatory for MPs: D01, 
- [x]  - The power plant field is not allowed for MPs: D20 & D99, D15, D02, E20
- [x]  - The power plant of a metering point is a valid GSRN/EAN18 code (checksum) that starts with digits ´57´
- [x]  - The product of a metering point is mandatory
- [x]  - The product of a metering point has domain values 8716867000030 (Active energy), 8716867000047 (Reactive energy), 8716867000016 (Active power), 8716867000023 (Reactive power), 5790001330606 (Fuel quantity), 5790001330590 (Tariff)
- [x]  - The energy time series measure unit of a metering point is mandatory
- [x]  - The street name of a Consumption and Production metering point is mandatory. It is optional for all other MP types
- [x]  - The product of a newly established metering point has default value 8716867000030 (Active energy) if metering point type not VE Production (D01), Analysis (D02), Exchange - Reactive energy (D20) or Internal use (D99)
- [x]  - The energy time series measure unit of a metering point has domain values K3 (kVArh), KWH (kWh), KWT (kW), MAW (MW), MWH (MWh), TNE (Tonne), Z03 (MVAr), Z14 (Danish tariff code)
- [x]  - The occurrence of a metering point has format YYYY-MM-DD 00:00:00 (local time)
- [x]  - The identification of a transaction is mandatory (Mrid on market activity record)
- [ ]  - The Metering Point created must become new (connected if metering point type is D04 or D15 when established) (Business rule)
- [x]  - The meter reading occurrence of a metering point must be PT1H or PT15M for all MPs besides D01 & D02, which can also be P1M
- [x]  - The sub type of a metering point is mandatory
- [x]  - The meter number of a metering point consists of maximal 15 characters
- [x]  - The meter number is mandatory for all MPs with subtype physical, otherwise not allowed
- [x]  - The kilowatt power limit of a metering point consists of maximal 6 digits
- [x]  - The ampere power limit of a metering point consists of maximal 6 digits
- [ ]  - The first consumer party name of a newly established metering point has default value '(ukendt)' (=unknown) (business rule for market roles)
- [x]  - The location description of a metering point consists of maximal 60 characters
- [x]  - The sub type of a metering point has domain values D01 (Physical), D02 (Virtual), D03 (Calculated)
- [ ]  - All mandatory master data attributes must be included for the specific metering point (See reference sheet)
- [ ]  - Disallowed master data cannot be included for the specific metering point (See reference sheet)
- [x]  - The capacity of a metering point consists of maximal 8 characters. Only digits and an optional decimal point are allowed. (only . allowed)
- [x]  - The connection type of a metering point has domain values D01 (Direct connected), D02 (Installation connected)
- [x]  - The disconnection type of a metering point has domain values D01 (Remote disconnection), D02 (Manual disconnection)
- [x]  - The capacity of Production metering points is mandatory 
- [x] The capacity of consumption metering points is mandatory  if net settlement group is not 0, else optional
- [x]  - The capacity field is not allowed for MP Types: E20, D02, D15, D20, D99
- [x]  - The connection type for consumption and production metering points is mandatory if net settlement group is not 0 (else not allowed)
- [x]  - The disconnection type For Consumption and Production metering points is mandatory, otherwise not allowed
- [x]  - Default value (KWH), all MP types but D01/D02/ D17/ D18, D20/D99 as provided
- [x]  - If a metering point is in net settlement group 3 or 6 then connection type must be Installation connected (D02). 
- [x]  - If a Consumption (E17) or Production (E18) metering point is not in net settlement group 0 or 99 then sub type must be Virtual (D02) or Calculated (D03).
- [x]  - If a Consumption metering point (E17) is not in net settlement group  0 or 99 then a power plant is required.
- [x]  - Meteringpoints of type D08, D09, D10, D11 and D12 must be Virtual (D02) or Calculated (D03). 
- [x]  - If type of metering point is Net consumption (D15) then meter reading occurrence must be Hourly (PT1H).
- [x]  - If type of metering point is Surplus production group 6 (D04) or Net consumption (D15) then meter reading occurrence must be Hourly (PT1H)
- [x]  - The AssetType has domain values D01 –D20 or D99 
- [x]  - For Production metering point (E18) the AssetType is mandatory. For a Consumption metering point (E17) in net settlement group not 0 the AssetType is mandatory, optional for other net settlement groups. AssetType is optional for TypeOfMP D01, D04 – D12, D17 and D18, else not allowed 
- [x]  - The format of the DARReference of the metering point should comply with the generic UUID format
- [x]  - The DAR reference field is mandatory for Consumption and Production MPs, otherwise optional
- [x]  - The product must be Reactive energy (8716867000047) if the metering point is of type Exchange - Reactive energy (D20)
- [x]  - The energy time series measure unit must be kWh or MWh if the master data applies to a metering point of type Other consumption (D17) or Other production (D18)
- [x]  - If type of metering point is Other consumption (D17) or Other production (D18) then sub type must be Physical (D01) or Virtual (D02).
- [ ]  - The meter reading occurrence of a D20 child metering point must be the same as the E20 parent metering point.
- [x]  - Subtype of a D20 metering point must be Physical (D01) or Virtual (D02) 
- [x]  - The energy time series measure unit of a D20 metering point must be K3 (kVArh)
- [x]  - It is not allowed to provide the source metering grid area if a metering point of type is Exchange - Reactive energy (D20).
- [x]  - It is not allowed to provide the target metering grid area if a metering point of type is Exchange - Reactive energy (D20).
- [ ]  - Handling create or change of an Electrical heating (D14)  metering point is not alloved in the business process

**Parent/child**
- [ ]  - The source metering grid area of a metering point is mandatory - type E20 or - type D20 and metering point is coupled to a parent or - not allowed (D20 standalone and other types) (Needs clarification, wait with this one)
- [ ]  - If a D20 child metering point is coupled to a parent, the subtype of E20 and D20 must be the same 
- [ ]  - For an Own production (D09) child metering point for which the parent metering point is not in net settlement group 0 or 99 the sub type must be Virtual (D02) or Calculated (D03).
- [ ]  - The Metering Point to which the master data applies must have a registered meter if subtype equals Physical
- [ ]  - The Metering Point to which the master data applies cannot have a registered meter if subtype differs from Physical.
- [ ]  - Only a Metering Point in group 1 and 2 can act as a parent (i.e. have coupled childs).
- [ ]  - Only a Metering Point in group 3 or 4 can act as a child of group 1 (i.e. have a coupled parent).
- [ ]  - Only a Metering Point in group 5 can act as a child of group 2 (i.e. have a coupled parent).
- [ ]  - The Grid Area of a child Metering Point must be the same as its parent

**Domain Rules**
- [x] - The metering point cannot already exist
- [x] - The metering grid area of a metering point must be an existing metering grid area
- [ ]  - The electrical heating of a newly established metering point has default value 0 (No) (business rule)

**Authentication Rules**
- [ ]  - Only registered and active grid operators are allowed
- [ ]  - The metering grid area of a metering point must belong to the correct grid operator (sender of message) 

__________________________________________
**Rules we need to discuss**
- [x]  -The physical status of a metering point is mandatory (Awaiting clarification)
- [x]  - The physical status of a metering point has domain values D03 (New), E22 (Connected) 
- [ ] - The source grid area of a E20 metering point must be an existing metering grid area (Wait with this one - we need to talk about grid areas) 
- [ ]  - The target metering grid area of a metering point is mandatory - type E20 Wait 
- [ ]  - The target grid area of a E20 metering point must be an existing metering grid area (Wait)
- [ ] - The sender of a message is mandatory (Handled in api gateway?)
- [ ]  - The sender of a message must currently be an existing and active market party (company) (Wait until we know where it is handled)
- [ ]  - The recipient of a message is mandatory (Handled in api gateway?)
- [ ]  - The recipient of a message must currently be an existing and active market party (company) (Wait until we know where it is handled)
- [ ]  - The sender role of a message must be DDM (Grid access provider) (handled in API gateway?)
- [ ]  - The data information must be received within the correct time period (Awaiting requirements)
- [ ]  - The address wash instructions of a Consumption and Production metering point is mandatory. It is not allowed for all other MP Types (Discuss)
- [ ]  - The identification of a transaction is unique for the sending market player (Note this confirms message transaction IDs are not globally unique, but unique per market participant) (probably not us - wait with this one)
- [ ]  ~~- The official address wash instructions a metering point has domain values D01 (Washable), D02 (Not washable)~~
- [ ]  - ~**The energy business process of a metering point is mandatory** ~ (Via synchronous handling)

**Comment by Christian-Meyer** [comment]
I have moved all validations that we need to discuss or that we are not implementing into its own section.
The section "Input Rules that are ready to be implemented" should only contain validations that we can implement at the moment.

**Comment by Christian-Meyer** [comment]
All rules besides "need to be discussed" have been validated by business and can be implemented

**Comment by erduna** [comment]
The first consumer party name of a newly established metering point has default value '(ukendt)' (=unknown) (business rule for market roles)

This is default behavior for MR domain when it listens to the MP Created event.

**Comment by erduna** [comment]
Updated master data sheet, see tab "Opret MP":
[Stamdata engros plus_vers. 6.XLSX](https://github.com/Energinet-DataHub/geh-metering-point/files/7473410/Stamdata.engros.plus_vers.6.XLSX)
