### ISSUE TITLE
Delete data in SQL database to make PowerBi faster 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-metering-point#739]
"Udvekslingsbekseder" dashboard in power BI is very slow, especially when you use the filters.

**Comment by MadsBloendAndersen** [comment]
@johevemi Will you take a look at this and come up with a solution you see fit. 

It is okay to remove some data from the database, as long as we can find message older than a month again (doesnt matter how long it takes to find them - probably not more than a day).

**Comment by MadsBloendAndersen** [comment]
@MadsBloendAndersen will set up a meeting with PowerBI team, and get their input.

**Comment by Christian-Meyer** [comment]
@MadsBloendAndersen Wrong repo? :)

**Comment by MadsBloendAndersen** [comment]
Issue moved to [Energinet-DataHub/eSett #20](https://github.com/Energinet-DataHub/eSett/issues/20) via [**ZenHub**](https://www.zenhub.com/)
