### ISSUE TITLE
Fix dato issue when connecting, updating and disconnecting MP's

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#764]
Currently it throws a "must have UTC+0 format error"" even though the date format is correct.

![image.png](https://images.zenhubusercontent.com/60bf67953ffc7e5c3e70b6a8/c6b0eac1-92ca-44d8-bbdc-73c1cab4cc15)

The error can be recreated by inserting a valid GSRN nr. into line 16 in connect message.

**Comment by Korgath** [comment]
@Christian-Meyer time was set to 23:00, but we have not entered summer time yet. Switched back to 22.00
