### ISSUE TITLE
Searching for an existing MP in GUI returns 404 not found (In T-001)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-metering-point#928]
Not possible to get an existing metering point in GUI. 
T-001: :x: Returns 404 no found.
U-001: :heavy_check_mark: Gets the metering point.

**Example from T-001**
MP ID: 571041421824913901

GET https://apim-shared-sharedres-t-001.azure-api.net/bff/v1/MeteringPoint/GetByGsrn?gsrnNumber=571041421824913901

MP in Metering Points DB: 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/815325b4-587b-45fd-88c9-3b338b56def8)

Application insigths [log](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227b7ffd68-d27e-4c75-936a-2653ecc36450%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-T-001%22%2C%22Name%22%3A%22appi-shared-sharedres-t-001%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7b7ffd68-d27e-4c75-936a-2653ecc36450%252FresourceGroups%252Frg-DataHub-SharedResouces-T-001%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-t-001%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22597db1b5-2a95-11ed-97db-6045bd950926%22%2C%22timestamp%22%3A%222022-09-02T07%3A59%3A30.921Z%22%2C%22cacheId%22%3A%22e88a8115-9eff-40e7-ab7d-a6ac018cedaa%22%2C%22eventTable%22%3A%22requests%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A1800000%2C%22endTime%22%3A%222022-09-02T08%3A06%3A42.872Z%22%7D%7D).

**Comment by Christian-Meyer** [comment]
I have checked if it is an auth. error(If user is connected to actor) but this does not seem to be the case.
